#启动端口
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#thymeleaf取消缓存
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev

#mybatis别名配置
mybatis:
  type-aliases-package: com.feicheng.blog.entity
#Sql语句的打印
logging:
  level:
    com.feicheng.blog.mapper: debug
  config:
    classpath: logback.xml
