
spring:
    #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/feiblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    #消息队列配置
  rabbitmq:
    host: 192.168.2.2
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: BLOG.EXCHANGE
    #redis缓存
  redis:
    host: 192.168.2.4
    database: 3

#图片上传
fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:   #缩略图
    width: 60
    height: 60
  tracker-list: #tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.2.8:22122


#自定义配置

#本人用户Email
myself:
  email: 1692454247@qq.com
  #本机使用IP地址
  address: http://127.0.0.1:8080/
  #图片上传地址
  image:
    address: http://192.168.2.8/

#文章基本参数
article:
  click:
    #起始位置
    page: 1
    #查询数量
    limit: 6
  #推荐文章
  commond:
    page: 1
    limit: 6